open_api_url : https://data.melbourne.vic.gov.au/api/records/1.0/search/

open_data_ingestion :
  pedestrian-counting-system-sensor-locations: 
    lookback : False
    remove_staged : True
    db_load_type : replace

  pedestrian-counting-system-monthly-counts-per-hour :
    lookback : True
    lookback_days : 2
    remove_staged : True
    db_load_type : replace